### PR TITLE
Fix: context menu is visible even when selection is collapsed

### LINKED ISSUE #2111: [Mobile] Context menu stay visible after Paste action
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.1.10

### Steps to reproduce

1. Enter text
2. Copy text
3. Try to Paste
4. Try to enter new text
5. Try to Paste

### Expected results

Context menu is hidden after each Copy/Paste action

### Actual results

Context menu is visible

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

Screenshot 2024-08-14 at 18 02 22

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### PR DESCRIPTION
**Pull request by CatHood0**
## Description

As the title says, the context menu (on mobile) is visible even if we write some extra text to try to hide it manually. 

#### Steps to reproduce:

* Select a text
* Write something (yeah, replace the selection)

And voilá, you will see the context menu is visible when it should be hide already.

## Related Issues

- *Fix #2111*

- [ ] ✨ **New feature:** Adds new functionality without breaking existing features.
- [x] 🛠️ **Bug fix:** Resolves an issue without altering current behavior.
- [ ] 🧹 **Code refactor:** Code restructuring that does not affect behavior.
- [ ] ❌ **Breaking change:** Alters existing functionality and requires updates.
- [ ] 🧪 **Tests:** Adds new tests or modifies existing tests.
- [ ] 📝 **Documentation:** Updates or additions to documentation.
- [ ] 🗑️ **Chore:** Routine tasks, or maintenance.
- [ ] ✅ **Build configuration change:** Changes to build or deploy processes.

### CODE REVIEW

File: lib/src/editor/raw_editor/raw_editor_state.dart [hunk 1]
```diff
@@ -1419,7 +1419,10 @@ class QuillRawEditorState extends EditorState
 
   void _updateOrDisposeSelectionOverlayIfNeeded() {
     if (_selectionOverlay != null) {
-      if (_hasFocus) {
+      if (!_hasFocus || textEditingValue.selection.isCollapsed) {
+        _selectionOverlay?.dispose();
+        _selectionOverlay = null;
+      } else if (_hasFocus) {
```
Comment (EchoEllet) [inline lib/src/editor/raw_editor/raw_editor_state.dart:1425]: It seems like a regression and the fix reverted the previous code, this issue could have been easily avoided if we were more cautious about the code review. See [this comment in #2026](https://github.com/singerdmx/flutter-quill/pull/2026/files#r1767596576).

Which is why I suggest to not merge PRs that don't explain the changes and why they were made, we're not familiar with the code, it's not documented or tested so we need to be more cautious.

Comment (CatHood0) [reply lib/src/editor/raw_editor/raw_editor_state.dart:1425]: > New changes need to be documented when needed. We need more rules and guidelines that we ask everyone to follow at some point, some of the changes that are not clear are introduced by PRs.

Yes, I agree. However, sometimes PRs are merged so quickly that there is not even time to ask or see the changes.
