### PR TITLE
Fix: LineHeight button to use MenuAnchor

### LINKED ISSUE #1981: LineHeight toolbar button popup menu appears disconnected
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.7

### Steps to reproduce

This is a good addition to flutter quill editor.

1. Enable showing line height toolbar button in example application:     (this.showLineHeightButton = true,)
2. Click button and popup menu appears in wrong place.

### Expected results

Popup menu should be connected to the toolbar button.
The other font selection buttons have the popup connected to the button.

### Actual results

Placement of the menu popup depends on the location of the button within the toolbar.
If the button is at the left then placement is usually correct.
If the button is at the right then placement is flush right which is OK.
If the button is somewhere in the middle, the popup appears a long distance to the right and disconnected from the button
(This is shown in the screenshot)

### Code sample

<details><summary>Code sample</summary>

```dart
simple_toolbar_configurations.dart
class QuillSimpleToolbarConfigurations
    this.showLineHeightButton = true,
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
Screenshot 2024-07-06 125947

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### PR DESCRIPTION
**Pull request by AtlasAutocode**
## Description

Fix: LineHeight button to use MenuAnchor. Modelled changes on that used for header toolbar button.
(There is no rush to merge this fix - whenever it is convenient.)

## Related Issues

- *Fix #1981*

## Additional notes
In my copious free time, I may look to see if font, size, header and lineheight buttons can be consolidated to use a common base class.

## Checklist

- [ X ] I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [ X ] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [ X ] I did not modify the `CHANGELOG.md` nor the package version in `pubspec.yaml` files.
- [ X ] All existing and new tests are passing.
- [ X ] I have run the commands in `./scripts/before_push.sh` and it all passed successfully

## Breaking Change

Does your PR require developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [ X ] No, this is *not* a breaking change.

### CODE REVIEW

File: lib/src/widgets/toolbar/buttons/select_line_height_dropdown_button.dart [hunk 1]
```diff
@@ -133,78 +134,61 @@ class _QuillToolbarSelectLineHeightStyleDropdownButtonState
...
-                )
-                .toList())
-        .then<void>(
-      (value) {
-        if (value != null) {
-          _onPressed(value);
-        }
-      },
-    );
+    return MenuAnchor(
```
Comment (CatHood0) [inline lib/src/widgets/toolbar/buttons/select_line_height_dropdown_button.dart:137]: These changes were there originally, but since the issue with MenuAnchor appearing below the keyboard became apparent, I made an ill-advised change, which created disadvantages.

The only thing I could say is that you have to take into account that the MenuAnchor produces this problem depending on the number of items and their size, so it could still be subject to change. 

For now MenuAnchor at least with LineHeight does not produce this error (at least as far as I tested it) so there should be nothing wrong with this change.

**Review by singerdmx — APPROVED** [review]
