### PR TITLE
Fix Multiline paste with attributes and embeds

### LINKED ISSUE #2072: I would like copying and pasting text with formatting on Android and iOS
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

copy and paste with formatting between different instances of flutter quill

### PR DESCRIPTION
**Pull request by AtlasAutocode**
## Description

When multiple lines of text with attributes and embeds are copied to the clipboard, they did not paste correctly into the QuillEditor.

## Related Issues

- *Fix #2072*

## Type of Change

- [ ] ✨ **New feature:** Adds new functionality without breaking existing features.
- [ X ] 🛠️ **Bug fix:** Resolves an issue without altering current behavior.
- [ ] 🧹 **Code refactor:** Code restructuring that does not affect behavior.
- [ ] ❌ **Breaking change:** Alters existing functionality and requires updates.
- [ X ] 🧪 **Tests:** Adds new tests or modifies existing tests.
- [ ] 📝 **Documentation:** Updates or additions to documentation.
- [ ] 🗑️ **Chore:** Routine tasks, or maintenance.
- [ ] ✅ **Build configuration change:** Changes to build or deploy processes.

### CODE REVIEW

File: lib/src/controller/quill_controller.dart [hunk 1]
```diff
@@ -572,6 +569,28 @@ class QuillController extends ChangeNotifier {
     return false;
   }
 
+  /// Internal method to allow unit testing
+  bool pasteUsingPlainOrDelta(String? clipboardText) {
```
Comment (EchoEllet) [inline lib/src/controller/quill_controller.dart:573]: Shouldn't this method annotated with `@visibleForTesting`?

Comment (EchoEllet) [reply lib/src/controller/quill_controller.dart:573]: Addressed in #2234.
