### PR TITLE
chore: fix deprecations of Flutter 3.27.0

### LINKED ISSUE #2409: why intl always resolve failed.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Why doesn't flutter_quill update its intl package dependency? It causes version conflicts. I noticed flutter_quill is using an intl package version from a year ago, even though flutter_quill itself maintains very active updates.

```log
/Users/xxx/Flutter/SDK/bin/flutter --no-color pub get
Resolving dependencies...
Because flutter_quill 10.8.5 depends on intl ^0.19.0 and no versions of flutter_quill match >10.8.5 <11.0.0, flutter_quill ^10.8.5 requires intl ^0.19.0.
So, because xxx depends on both intl ^0.20.1 and flutter_quill ^10.8.5, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on intl: flutter pub add intl:^0.19.0
Process finished with exit code 1
```
image

### PR DESCRIPTION
**Pull request by EchoEllet**
## Description

*Migrate deprecations of Flutter 3.27, fix analysis warnings, update the example's `pubspec.lock`, and update outdated `intl` constraint.*

## Related Issues

- *Fix #2409*

## Type of Change

- [ ] ✨ **Feature:** New functionality without breaking existing features.
- [ ] 🛠️ **Bug fix:** Resolves an issue without altering current behavior.
- [ ] 🧹 **Refactor:** Code reorganization, no behavior change.
- [ ] ❌ **Breaking:** Alters existing functionality and requires updates.
- [x] 🧪 **Tests:** New or modified tests
- [ ] 📝 **Documentation:** Updates or additions to documentation.
- [x] 🗑️ **Chore:** Routine tasks, or maintenance.
- [ ] ✅ **Build configuration change:** Build/configuration changes.

### CODE REVIEW

File: lib/src/editor_toolbar_shared/color.dart [hunk 1]
```diff
@@ -17,6 +17,18 @@ Color hexToColor(String? hexString) {
   return Color(int.tryParse(buffer.toString(), radix: 16) ?? 0xFF000000);
 }
 
+// Without the hash sign (`#`).
```
Comment (EchoEllet) [inline lib/src/editor_toolbar_shared/color.dart:20]: FYI: I used `//` instead of `///` here because those comments don't count as doc comments. The preference is to either fully document something or not count it as documented, which allows us to see all APIs that miss doc comments to keep it maintainable.

For more details: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#answer-your-own-questions-straight-away

File: pubspec.yaml [hunk 2]
```diff
@@ -40,7 +40,7 @@ dependencies:
   quiver: ^3.2.0
   meta: ^1.7.0
   html: ^0.15.0
-  intl: ^0.19.0
+  intl: '>=0.19.0 <0.21.0'
```
Comment (EchoEllet) [inline pubspec.yaml:43]: Fixing https://github.com/singerdmx/flutter-quill/issues/2409 and to avoid pub scores loss after 30 days.
