### PR TITLE
Fix block multi-line selection style

### LINKED ISSUE #1862: Multi-line style identification bug
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

master

### Steps to reproduce

Select some multi-line text first part of which is non-bold while second part is bold.

### Expected results

The selection style is shown as non-bold since not all the selected text is bold.

For example, it works fine if selection covers single line only. It also works fine if the first part is bold while the second is not.

### Actual results

The selection style is shown as bold.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

**Bug:**

Multiline style identification bug

**Correct behavior:**

Multiline style identification ok

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### PR DESCRIPTION
**Pull request by AtlasAutocode**
## Description

Resolve problems with style selection for multi-line selections involving block styles.
Improved maintainability by refactoring toolbar buttons to derive from common base class.

## Related Issues

- *Fix #1862*
- *Related #1861, #1863, #1846*

## Improvements
Refactored toolbar buttons (DRY methodology) to improve maintainability and resolve Issue 1862 for multiple use cases.
Class QuillToolbarCommonButtonState holds common access to: controller, options, tooltip, iconSize, iconFactor, iconTheme and afterButtonPressed. Toolbar buttons derive from common base class using generic type definitions.
Enabled focus to be restored to editor after toolbar button action.
## Checklist

- [ X ] I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [ X ] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [ X ] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [ X ] All existing and new tests are passing.
- [ X ] I have run the commands in `./scripts/before_push.sh` and it all passed successfully

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [ X ] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by ellet0** [comment]
Thank you for the cleanup, It was much needed and makes the code a lot cleaner for better maintainability, I always wanted to do this but never really found the time, you even added tests, I appreciate your help

**Comment by AtlasAutocode** [comment]
Issue 1861 was not fixed. This PR **related** to that issue with regard to the style selection but did not fix the positioning of the popup.

Styles for multiline with gap: It appears that blank lines do not have a style and hence collectStyles removes the bold. I will look into it.

**Comment by AtlasAutocode** [comment]
Handling style over blank lines was straight forward to fix. What was difficult was selections that started on a blank line!
I have issued a PR for link handling that included what I hope will fix this issue.

File: lib/src/widgets/editor/editor.dart [hunk 1]
```diff
@@ -172,6 +172,7 @@ class QuillEditorState extends State<QuillEditor>
   @override
   void initState() {
     super.initState();
+    widget.configurations.controller.editorFocusNode ??= widget.focusNode;
```
Comment (EchoEllet) [inline lib/src/widgets/editor/editor.dart:175]: Are we having the `FocusNode` in both `QuillController` and `QuillEditor`? We also need more docs and discussion about this. It looks like we're also reviewing the changes quickly previously.

File: lib/src/widgets/quill/quill_controller.dart [hunk 2]
```diff
@@ -25,14 +25,17 @@ class QuillController extends ChangeNotifier {
...
     this.readOnly = false,
+    this.editorFocusNode,
   })  : _document = document,
         _selection = selection;
 
   factory QuillController.basic(
       {QuillControllerConfigurations configurations =
-          const QuillControllerConfigurations()}) {
+          const QuillControllerConfigurations(),
+      FocusNode? editorFocusNode}) {
```
Comment (EchoEllet) [inline lib/src/widgets/quill/quill_controller.dart:35]: I still don't get why we're splitting things randomly without explaining them or documenting them, is the performance our main concern with the usage of the `const` keyword? It looks like we're worrying about such improvements that doesn't make any real difference in the real world when we have real performance issues.

File: test/widgets/controller_test.dart [hunk 3]
```diff
@@ -355,5 +355,61 @@ void main() {
       expect(controller.document.length, 6,
           reason: 'Cut not permitted on readOnly document');
     });
+
```
Comment (EchoEllet) [inline test/widgets/controller_test.dart:358]: Thank you for adding new unit tests, it was really needed.

File: lib/src/widgets/toolbar/buttons/link_style_button.dart [hunk 4]
```diff
@@ -54,45 +62,6 @@ class QuillToolbarLinkStyleButtonState
...
-  QuillToolbarBaseButtonOptions? get baseButtonExtraOptions {
-    return context.quillToolbarBaseButtonOptions;
-  }
-
-  String get tooltip {
-    return options.tooltip ??
-        baseButtonExtraOptions?.tooltip ??
-        context.loc.insertURL;
-  }
-
```
Comment (EchoEllet) [inline lib/src/widgets/toolbar/buttons/link_style_button.dart:95]: Unfortunately this is still duplicated code across many buttons, I will address it in future breaking change release.

**Review by EchoEllet — COMMENTED** [review]
Just one minor thing that we really need to consider.

File: lib/src/widgets/quill/quill_controller.dart [hunk 5]
```diff
@@ -485,6 +488,9 @@ class QuillController extends ChangeNotifier {
   List<OffsetValue> get pasteStyleAndEmbed => _pasteStyleAndEmbed;
   bool readOnly;
 
+  /// Used to give focus to the editor following a toolbar action
+  FocusNode? editorFocusNode;
+
```
Comment (EchoEllet) [inline lib/src/widgets/quill/quill_controller.dart:493]: @AtlasAutocode 

Why this can be accessed from the `QuillController`? The editor focus node is meant for the `QuillEditor`, the developer can create it, pass it to the editor, and manage it, I will remove it in `11.0.0`, please let me know if there is a reason.
