### PR TITLE
Toolbar button styling to reflect cursor position when running on desktops with keyboard to move caret.

### LINKED ISSUE #1775: flutter quill Bold not work
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.1

### Steps to reproduce

Windows platform ,
download the https://github.com/singerdmx/flutter-quill/ 
run the example, the bold button does not correctly work 

### Expected results

When the bold button clicked, the text bold or cancel bold

### Actual results

the bold button does not correctly work 

### Code sample

<details><summary>Code sample</summary>

```dart
  QuillToolbarToggleStyleButton(
                    options: const QuillToolbarToggleStyleButtonOptions(),
                    controller: controller,
                    attribute: Attribute.bold,
                  ),

QuillEditor.basic(
              configurations: QuillEditorConfigurations(
                controller: _controller,
                padding: const EdgeInsets.all(16),
              ),
            ),

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/singerdmx/flutter-quill/assets/36724474/8150293b-09c7-4d6d-a50f-5d34ecb70997

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### LINKED ISSUE #1786: QuillToolbarBaseButtonOptions did'nt work
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

^9.3.3

### Steps to reproduce

1. Only use the code based on the photo I sent

### Expected results

I was expecting that if I use the base, then I don't need to change the style of the buttons one by one.

### Actual results

QuillToolbarBaseButtonOptions did'nt work. I must change the toolbar button option one by one.

### Code sample

<details><summary>Code sample</summary>

```dart
      configurations: QuillToolbarConfigurations(
        buttonOptions: QuillSimpleToolbarButtonOptions(
          base: QuillToolbarBaseButtonOptions(
            iconTheme: QuillIconTheme(
              iconButtonSelectedData: IconButtonData(
                style: IconButton.styleFrom(
                  foregroundColor: Colors.red,
                  backgroundColor: Colors.green,
                ),
                color: Colors.white,
                highlightColor: Colors.red,
                focusColor: Colors.green,
              ),
              iconButtonSelectedStyle: ButtonStyle(
                backgroundColor: MaterialStateProperty.all(Colors.red),
                iconColor: MaterialStateProperty.all(Colors.green),
              ),
            ),
            iconSize: 10,
          ),
        ),
        sharedConfigurations: QuillSharedConfigurations(
          locale: Get.locale
        ),
      ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

image

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### PR DESCRIPTION
**Pull request by AtlasAutocode**
## Description

Proposed changes make the toolbar buttons selection state reflect the styling as the cursor is moved. Using desktop (Windows) keyboard cursor keys to move the caret position (without selecting text).

- Fix inline style tracking: When cursor is moved into a region of bold, the bold style is correctly recognized and reflected in the toolbar status. Problem: When the cursor keys move the caret out of the bold region, the bold style is not cleared and cannot be removed.

- Fix: toggle_style_button failed to call default afterButtonPressed in base button settings. Constructor called options.afterButtonPressed rather than the class function afterButtonPressed that defaults to a call to QuillToolbarBaseButtonOptions.

- Fix: quill_icon_button build when isSelected did not call afterButtonPressed (expected same action as when not selected).

- Fix: QuillController _updateSelection removed param=source because not used; added new param insertNewline to recognize when a newline entered and maintain the correct inline style by correctly setting toggledStyle; updated replaceText to call _updateSelection for newline.

- Fix: document.dart collectStyle:  Click at the start of a line (of bold text), user would expect the style to be the visible style of the line including inline styles. Also requires updating insert.dart PreserveInlineStylesRule to recognize if inserting text at start of line and use attributes from the first char on line

- Fix: color_button : Add afterPressed param to QuillToolbarIconButton

## Related Issues

- *Fix #1786*  QuillToolbarBaseButtonOptions now called

- *Fix #1775*  Toolbar bold button now tracks cursor position

## Suggestions
QuillController (public function) updateSelection also does not use the ChangeSource parameter.
ChangeSource enum does not appear to be used anywhere - is this deprecated or am I missing something?

## Checklist

- [X] I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [X] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [X] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [X] All existing and new tests are passing.
- [X] I have run the commands in `./scripts/before_push.sh` and it all passed successfully

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [X] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by singerdmx** [comment]
```
Run dart format --set-exit-if-changed .
Formatted lib/src/widgets/quill/quill_controller.dart
Formatted 260 files (1 changed) in 1.33 seconds.
Error: Process completed with exit code 1.
```

File: example/lib/screens/quill/my_quill_toolbar.dart [hunk 1]
```diff
@@ -223,24 +223,24 @@ class MyQuillToolbar extends StatelessWidget {
               '40': '40.0'
             },
             // headerStyleType: HeaderStyleType.buttons,
-            // buttonOptions: QuillSimpleToolbarButtonOptions(
```
Comment (singerdmx) [inline example/lib/screens/quill/my_quill_toolbar.dart:226]: is this change needed?

**Comment by singerdmx** [comment]
@ellet0 I am unsure about this PR. Could you please take a look? Thanks!

**Comment by ellet0** [comment]
> @ellet0 I am unsure about this PR. Could you please take a look? Thanks!

I'm not sure too about the changes in the insert rule and the document file

The code is getting more and more messy
Only the original authors can understand it

And with all the changes that have been made, I doubt they can understand it now

I can understand the other changes

**Comment by ellet0** [comment]
> @ellet0 I am unsure about this PR. Could you please take a look? Thanks!

I'm not sure too about the changes in the insert rule and the document file

The code is getting more and more messy
Only the original authors can understand it

I haven't made any changes to the base of the library (in the document, raw editor widget, the rules, etc...)

I can understand the other changes

**Comment by ellet0** [comment]
Please revert all the unnecessary comments that have been made like the ones in the example folder

**Review by ellet0 — CHANGES_REQUESTED** [review]
Please revert all the unnecessary comments that have been made like the ones in the example folder

**Comment by AtlasAutocode** [comment]
Changes made and submitted.
This is my first contribution - do I need to do something??

**Comment by singerdmx** [comment]
@ellet0 can you check this PR again?

**Review by singerdmx — APPROVED** [review]

**Comment by singerdmx** [comment]
```
Run dart format --set-exit-if-changed .
Formatted lib/src/widgets/quill/quill_controller.dart
Formatted 261 files (1 changed) in 1.2[8](https://github.com/singerdmx/flutter-quill/actions/runs/8544426268/job/23524750239?pr=1801#step:13:9) seconds.
Error: Process completed with exit code 1.
```

**Review by singerdmx — CHANGES_REQUESTED** [review]
Please fix formatting issue

**Comment by ellet0** [comment]
> @ellet0 can you check this PR again?

I'm not familiar with most of the code, and I don't understand why it's what it's and why this change could solve the issues mentioned.

**Comment by singerdmx** [comment]
> > @ellet0 can you check this PR again?
> 
> I'm not familiar with most of the code, and I don't understand why it's what it's and why this change could solve the issues mentioned.

We just need to test if it fixes the issue the PR mentioned.
If there is issue we can always rollback.
