### PR TITLE
Fix: QuillToolbarToggleStyleButton Switching failure

### LINKED ISSUE #2216: QuillToolbarToggleStyleButton， QuillToolbarToggleStyleButton Switching failure  on macOS
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

flutter_quill: ^10.5.16

### Steps to reproduce

First, add a task list and input the content, then press enter to create a new empty task list. 
Then, delete this new task list and return to the first list.
 Finally, switch to QuillToolbarToggleCheckListButton
At this point, clicking on the switch event will render it invalid

### Expected results

Click to switch states correctly

### Actual results

First, add a task list and input the content, then press enter to create a new empty task list. Then, delete this new task list and return to the first list. Finally, switch to QuillToolbarToggleCheckListButton
At this point, clicking on the switch event will render it invalid

### Code sample

<details><summary>Code sample</summary>
I am using the demo from the Flutter_quill library
```dart
      QuillToolbarToggleCheckListButton(
                    controller: controller,
                  ),
                  QuillToolbarToggleStyleButton(
                    controller: controller,
                    attribute: Attribute.ol,
                  ),
                  QuillToolbarToggleStyleButton(
                    controller: controller,
                    attribute: Attribute.ul,
                  ),
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
[新标签页.webm](https://github.com/user-attachments/assets/4d02ff04-bfbe-4930-a07d-12c1353bdddf)

### PR DESCRIPTION
**Pull request by AtlasAutocode**
## Description

Fix: QuillToolbarToggleStyleButton Switching failure for block attributes

## Related Issues

- *Fix #2216*

## Type of Change

- [ ] ✨ **New feature:** Adds new functionality without breaking existing features.
- [ X ] 🛠️ **Bug fix:** Resolves an issue without altering current behavior.
- [ ] 🧹 **Code refactor:** Code restructuring that does not affect behavior.
- [ ] ❌ **Breaking change:** Alters existing functionality and requires updates.
- [ ] 🧪 **Tests:** Adds new tests or modifies existing tests.
- [ ] 📝 **Documentation:** Updates or additions to documentation.
- [ ] 🗑️ **Chore:** Routine tasks, or maintenance.
- [ ] ✅ **Build configuration change:** Changes to build or deploy processes.

### CODE REVIEW

**Comment by EchoEllet** [comment]
Thank you for addressing the `pasteUsingPlainOrDelta()` issue.

As a side note, we should avoid exposing new APIs to the public, when a new property or function is introduced, it should be experimental for a while before promoting to stable when something is deprecated it's probably better to create extension on the class and move the deprecated members there instead of having them in the main file, we usually want to make more members private unless there is a reason to not, or moving them into a separate file without exporting the internal file.

Also using `@visibleForTesting` is useful. It can be considered as a breaking change if that API commonly used.

File: lib/src/controller/quill_controller.dart [hunk 1]
```diff
@@ -603,7 +601,7 @@ class QuillController extends ChangeNotifier {
     return false;
   }
 
-  /// Internal method to allow unit testing
+  @visibleForTesting
```
Comment (EchoEllet) [inline lib/src/controller/quill_controller.dart:604]: Update: I haven't noticed it but it seems this function is used internally, `@visibleForTesting` is for code that will only used in tests and should not used internally in the package itself or by users. Instead should use `@internal`
