### PR TITLE
if magnifier removes toolbar, restore it when it is hidden

### LINKED ISSUE #2046: Selection menu doesn't display after drag
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.0.2

### Steps to reproduce

1. Create a note with lots of text.
2. Long press a word 
3. Drag one of the selection handles
4. End the drag

### Expected results

I'm expecting the selection menu to reappear after the drag is finished.

### Actual results

The selection menu does not reappear.  So after selecting text, no way to cut/copy.

### Code sample

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mtallenca**
## Description

Magnifier is removing selection context menu, but not restoring the menu after it's dismissed. This PR fixes that bug

- *Fix #2046*

## Type of Change

- [ ] ✨ **New feature:** Adds new functionality without breaking existing features.
- [x] 🛠️ **Bug fix:** Resolves an issue without altering current behavior.
- [ ] 🧹 **Code refactor:** Code restructuring that does not affect behavior.
- [ ] ❌ **Breaking change:** Alters existing functionality and requires updates.
- [ ] 🧪 **Tests:** Adds new tests or modifies existing tests.
- [ ] 📝 **Documentation:** Updates or additions to documentation.
- [ ] 🗑️ **Chore:** Routine tasks, or maintenance.
- [ ] ✅ **Build configuration change:** Changes to build or deploy processes.

### CODE REVIEW

File: lib/src/editor/widgets/text/text_selection.dart [hunk 1]
```diff
@@ -181,6 +181,7 @@ class EditorTextSelectionOverlay {
 
   /// A copy/paste toolbar.
   OverlayEntry? toolbar;
+  bool _restoreToolbar = false;
```
Comment (EchoEllet) [inline lib/src/editor/widgets/text/text_selection.dart:184]: Is `_restoreToolbar` something specific to the magnifier or something only needed to fix an issue related to the magnifier and is not meant to be used outside of this feature?

**Review by EchoEllet — COMMENTED** [review]
@mtallenca Thank you for the quick fix, working on moving this feature into it's own separate file so more details would be helpful to address it correctly.

File: lib/src/editor/widgets/text/text_selection.dart (hunk 1 above)
Comment (EchoEllet) [reply lib/src/editor/widgets/text/text_selection.dart:184]: If yes, we probably need a better way to document it or maybe more specific name:

```dart
/// Restore the selection context menu after the magnifier is dismissed.
bool _restoreToolbar = false;
```

Do you have suggestions?

**Comment by mtallenca** [comment]
This is a flag only used by the magnifier.  If the magnifier is going to
hide the toolbar, it needs to restore the toolbar when dismissed.  A better
name would be _restoreToolbarAfterMagnifier

**Comment by EchoEllet** [comment]
Thank you for confirming.
