### PR TITLE
Fix: RTL issues

### LINKED ISSUE #1928: problems when using languages ​​that use ltr instead of rtl
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.4.2

### Steps to reproduce

problem with languages ​​that use ltr instead of rtl,   DirectionAttribute('ltr');
When I touch the enumerated list or checkbox option, even when using ltr in languages ​​like Hebrew, the checkboxes and enumerated lists do not change, they remain in the position as if using rtl

### Expected results

checkbox and the list number go to the beginning of the line on the right side

### Actual results

checkbox and list number are at the beginning of the line on the left side

### Code sample

default quill

### Screenshots or Video

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by CatHood0**
## Description

As we know, we always have issues related with the RTL directionality. At this moment, the current implementation of List, Checkbox or Blockquote, force the direction to be LTR, even if the system language is a RTL. 

_To test this i use some languages as **hebrew** or **arabic** that are RTL (as far i know)_

### Before these changes

Before 1 Before 2(1)

### After these changes

After1(1) After2 After3

## Related Issues

*Fix #1928*

- [ ] ✨ **New feature:** Adds new functionality without breaking existing features.
- [x] 🛠️ **Bug fix:** Resolves an issue without altering current behavior.
- [ ] 🧹 **Code refactor:** Code restructuring that does not affect behavior.
- [ ] ❌ **Breaking change:** Alters existing functionality and requires updates.
- [ ] 🧪 **Tests:** Adds new tests or modifies existing tests.
- [ ] 📝 **Documentation:** Updates or additions to documentation.
- [ ] 🗑️ **Chore:** Routine tasks, or maintenance.
- [ ] ✅ **Build configuration change:** Changes to build or deploy processes.

## Suggestions

We really **need** to avoid harcode the widgets on the editor. 

I'll try to separate the logic to another file and make more extensible soon

### CODE REVIEW

File: lib/src/common/utils/directionality.dart [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+    'yi', // Yiddish
+    'sd', // Sindhi
+    'ug', // Uyghur
+  ];
+  return rtlLanguages.contains(locale.languageCode);
+}
+
+bool isRTL(BuildContext context) {
+  return isRTLLanguage(Localizations.localeOf(context));
+}
```
Comment (EchoEllet) [inline lib/src/common/utils/directionality.dart:25]: I'm not sure if there is a reason or if we're already using `Directionality.of(context)` instead?

Comment (CatHood0) [reply lib/src/common/utils/directionality.dart:25]: Can you explain more about it? I'm using these functions to verify first if the language of the system is a RTL language. Does `Directionality.of(context)` already do this?

Comment (EchoEllet) [reply lib/src/common/utils/directionality.dart:25]: It does and it's compatible with Flutter, it supports the [Directionality](https://api.flutter.dev/flutter/widgets/Directionality-class.html) widget and should work in case the user changes the local or the direction

**Comment by Eng-Mohamed-Elsayed** [comment]
ok how can add button ltr or rtl

**Comment by jonasbernardo** [comment]
It doesn't work, watch the video, its ontap only works as if it were in the ltr position

https://github.com/user-attachments/assets/ccd43be3-9977-48ee-b057-5ff0580147fa
