### PR TITLE
fix(macos): Implement actions for ExpandSelectionToDocumentBoundaryIntent and ExpandSelectionToLineBreakIntent to use keyboard shortcuts, unrelated cleanup to the bug fix.

### LINKED ISSUE #1192: [Desktop] Error when using selection shortcut on Mac
Hello,
I'm getting the following 2 errors when using ```command + shift + arrow``` shortcuts on MacOS:

Error 1:
```Unable to find an action for an Intent with type ExpandSelectionToDocumentBoundaryIntent in an Actions widget in the given context.```
Triggered by ```command + shift + arrow up``` and ```command + shift + arrow down``` (Platform shortcut for moving selection from current position to start or end of text)

Error 2:
```Unable to find an action for an Intent with type ExpandSelectionToLineBreakIntent in an Actions widget in the given context.```
Triggered by ```command + shift + arrow right``` and ```command + shift + arrow left``` (Platform shortcut for moving selection from current position to start of end of line.)

### PR DESCRIPTION
**Pull request by EchoEllet**
## Description

*Implement actions for [ExpandSelectionToDocumentBoundaryIntent](https://github.com/flutter/flutter/blob/2663184aa79047d0a33a14a3b607954f8fdd8730/packages/flutter/lib/src/widgets/text_editing_intents.dart#L147-L162) and [ExpandSelectionToLineBreakIntent](https://github.com/flutter/flutter/blob/2663184aa79047d0a33a14a3b607954f8fdd8730/packages/flutter/lib/src/widgets/text_editing_intents.dart#L164-L181) in addition to unrelated cleanup that is not required to have the bug fix.*

This PR will be updated soon, see #1192 for more details about the issue.

## Related Issues

- *Fix #1192*
- *Related #1937*
- *Related #2288*

`ExtendSelectionToNextParagraphBoundaryOrCaretLocationIntent` is also missing and will throw when pressing (option + shift + arrow up/down).

## Type of Change

- [ ] ✨ **New feature:** Adds new functionality without breaking existing features.
- [x] 🛠️ **Bug fix:** Resolves an issue without altering current behavior.
- [ ] 🧹 **Code refactor:** Code restructuring that does not affect behavior.
- [ ] ❌ **Breaking change:** Alters existing functionality and requires updates.
- [ ] 🧪 **Tests:** Adds new tests or modifies existing tests.
- [ ] 📝 **Documentation:** Updates or additions to documentation.
- [ ] 🗑️ **Chore:** Routine tasks, or maintenance.
- [ ] ✅ **Build configuration change:** Changes to build or deploy processes.

## Suggestions

Not for merge yet.

## TODO

- [ ] Explain the changes
- [ ] Add tests, improve docs, and clear the Todos in code.

### CODE REVIEW

**Comment by EchoEllet** [comment]
@CatHood0 I will address the change of
`QuillKeyboardServiceWidget` directly in this PR, worrying about having a clean history, separation, and organization of changes is not our first priority at the moment, I keep forgetting about adding this to the Todo and already forgot many things since I delay them later, my TODO is already full.

The support for shortcuts is not clean enough, some of them are overridable:

```dart
  HideSelectionToolbarIntent:
        _makeOverridable(QuillEditorHideSelectionToolbarAction(this)),
    UndoTextIntent: _makeOverridable(QuillEditorUndoKeyboardAction(this)),
    RedoTextIntent: _makeOverridable(QuillEditorRedoKeyboardAction(this)),
```

Some of them do start with `QuillEditor` prefix and some of them do not:

```dart
    ToggleTextStyleIntednt: _formatSelectionAction,
    IndentSelectionIntent: _indentSelectionAction,
    QuillEditorApplyHeaderIntent: _applyHeaderAction,
    QuillEditorApplyCheckListIntent: _applyCheckListAction,
    // TODO: Double check and see if those and related should be overridable
    QuillEditorApplyLinkIntent: QuillEditorApplyLinkAction(this),
    ScrollToDocumentBoundaryIntent: NavigateToDocumentBoundaryAction(this),
```

Others are not instantiated directly and have private member and the only usage is in the shortcuts:

```
    ToggleTextStyleIntent: _formatSelectionAction,
    IndentSelectionIntent: _indentSelectionAction,
    QuillEditorApplyHeaderIntent: _applyHeaderAction,
    QuillEditorApplyCheckListIntent: _applyCheckListAction,
```

It's not clear how should we name things, we need to agree on something, each class is named very differently without conventions or guidelines, it's also not clear that if we should add the `SingleActivator` (see [#1937 comment](https://github.com/singerdmx/flutter-quill/pull/1937/files#r1773712588)) or if they are already registered with Flutter, or if we're using something somewhere that do register those, why they those actions are missing in the first place? It's causing issues on the desktop with keyboard shortcuts.

In addition to other questions and issues, I didn't register them in the TODOs.

The file `default_single_activator_actions.dart` should also be somewhere inside `raw_editor`.

**Comment by EchoEllet** [comment]
It seems that there are even more important things to clean up, I have also noticed some duplicated logic, and a new update will be soon however it's not related to this PR so it might be confusing to review. I have tried to separate it into a new PR though decided not to.

**Comment by EchoEllet** [comment]
> or if we're using something somewhere that do register those, why they those actions are missing in the first place

It seems that we're using [`intentForMacOSSelector()`](https://github.com/flutter/flutter/blob/stable/packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart#L587-L648) from Flutter inside the `raw_editor_state.dart` without implementing the actions for each intent.

image

image

We need to file an issue for this and fix them all in a clean way so we don't lost track of this.

File: lib/src/editor/raw_editor/keyboard_shortcuts/default_single_activator_intents.dart [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+    SingleActivator(
+      LogicalKeyboardKey.home,
+      control: !_isDesktopMacOS,
+      meta: _isDesktopMacOS,
+    ): const ScrollToDocumentBoundaryIntent(forward: false),
+    SingleActivator(
+      LogicalKeyboardKey.end,
+      control: !_isDesktopMacOS,
+      meta: _isDesktopMacOS,
+    ): const ScrollToDocumentBoundaryIntent(forward: true),
```
Comment (EchoEllet) [inline lib/src/editor/raw_editor/keyboard_shortcuts/default_single_activator_intents.dart:165]: Those two included in #1937. I wasn't and still not sure if this is needed, seems to be redudent though.

File: lib/src/editor/raw_editor/raw_editor_actions.dart [hunk 2]
```diff
@@ -268,6 +268,113 @@ class QuillEditorExtendSelectionOrCaretPositionAction extends ContextAction<
...
+      extentOffset: targetLineBreak,
+    );
+
+    return Actions.invoke(
+      context ?? (throw StateError('BuildContext should not be null.')),
+      UpdateSelectionIntent(
+        state.textEditingValue,
+        newSelection,
+        SelectionChangedCause.keyboard,
+      ),
```
Comment (EchoEllet) [inline lib/src/editor/raw_editor/raw_editor_actions.dart:373]: Will need to know if this functionality already exist as a function to call, prefer to not repeat it twice, it can be confusing for other developers and for me in the future.

Comment (EchoEllet) [reply lib/src/editor/raw_editor/raw_editor_actions.dart:373]: Related [_linebreak()](https://github.com/singerdmx/flutter-quill/blob/master/lib/src/editor/raw_editor/keyboard_shortcuts/editor_keyboard_shortcut_actions.dart#L56-L80)

**Review by AtlasAutocode — COMMENTED** [review]
> The support for shortcuts is not clean enough, some of them are overridable:

Just a comment: I have had a brief encounter with _makeOverridable and was surprised by how it works:

Overridable means it can be overridden by **_prior_** implementations. That is exactly the opposite of what I understand by the term.

For example: Widget build Stack:
Widget 1 overridable action
Widget 2 overridable action
Widget 3 uses action from Widget 1! Because the prior implementation takes priority.

In order for the implementation in Widget 2 to correct a defect in Widget 1's implementation, it has to not use _makeOverridable.

I hope I am wrong in this. 

In my case, I seem to recollect that there was an error in how Flutter handled a macOS shortcut key and since Flutter was at the top of the rendering stack it always took priority so my fix would never work if I used _makeOverridable!

**Comment by EchoEllet** [comment]
Our current code is quite confusing, even after the cleanup we have `editor_keyboard_shortcut_actions.dart` and `raw_editor_actions.dart`, `ScrollToDocumentBoundaryIntent` is already registered intent by default so including it in:

```dart
  SingleActivator(
      LogicalKeyboardKey.home,
      control: !_isDesktopMacOS,
      meta: _isDesktopMacOS,
    ): const ScrollToDocumentBoundaryIntent(forward: false),
    SingleActivator(
      LogicalKeyboardKey.end,
      control: !_isDesktopMacOS,
      meta: _isDesktopMacOS,
    ): const ScrollToDocumentBoundaryIntent(forward: true),
```

Doesn't make any difference, I still want to know if this macOS specific and why we don't need to register a activator for it before moving further.

Was added in #1937.

**Review by singerdmx — APPROVED** [review]

**Comment by EchoEllet** [comment]
See #2288, while cleaning up, I'm having even more questions and the answers are not clear, I have spent almost one or two days trying to fix a minor bug, the bug has been fixed without fixing the related code quality issues, I prefer to completely rewrite the Keyboard shortcuts with their actions and intent instead and might do in a separate PR or might improve it later.

Hopefully was able to move around 170 lines of code from `QuillRawEditorState`.

@CatHood0 @AtlasAutocode If you can review the PR, once addressing all the changes, will merge this PR for now.

**Comment by CatHood0** [comment]
Sorry I haven't been able to fix a few issues yet. I've had a busy time these past few days. I'll take the time tonight to do some code reviews and fix issues that were already on my list.
